name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Se activa al hacer push a la rama main
  pull_request:
    branches:
      - main  # También se activa en PRs hacia la rama main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]  # Pruebas en tres versiones de Node.js
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: [lint, test]  # Solo se ejecuta si lint y test pasan correctamente
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --token=$VERCEL_TOKEN --yes
